version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD=yes is recommended only for development.
      - MARIADB_ROOT_PASSWORD=passx123

volumes:
  mariadb_data:
    driver: local
